id: P474718A5
initial_creation_type: input
source_metadata:
  title: Taking Refuge Series
  language: de
  description: 'Texts related to the practice of taking refuge (skyabs ''gro):'
  volume:
    ea7530d2e5b648bba0ac2c8e991107ee:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Practices
    508844cb22ab4ac7b8fcd0f31e448957:
      title: The Outer, Inner and Secret Refuge Prayer
      parent: Practices
    d0a01b14d8c64c6d8c366236bb5f69f3:
      title: The Fourfold 'Manam' Refuge
      parent: Practices
    8bc4ad9e33ec494a8db19a38ae83e2eb:
      title: Verses of Refuge and Bodhicitta
      parent: Practices
    5280bcccf36d453b9a3345db8c240638:
      title: The Outer, Inner and Secret Refuge Practice of the Mahāsiddha Thangtong
        Gyalpo
      parent: Practices
    d08fda0e5c394d4c87056c344ba2a8dc:
      title: A Brief Commentary on the Refuge & Bodhichitta Prayer known as Sangyé
        Chö Tsok Ma
      parent: Commentaries
    d8f01b6957054cf39e0fd0d784cea5c9:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Commentaries
created_at: '2022-03-01T06:01:31.577624'
last_modified_at: '2022-03-01T06:01:31.577626'
